### ISSUE TITLE
Remove clutter from plots

### ISSUE THREAD

**Issue by tashrifbillah** [ml-energy/leaderboard-v2#11]
This chart goes against the principles of data visualization:

![image](https://github.com/ml-energy/leaderboard/assets/35086881/9713e977-4c6d-4af6-bcfd-68b86f874e48)

Recommendation to improve:

1. Remove all static texts around circles
2. Put the texts as tooltips so they pop up only when user hovers over them (I now see that the tooltips are present already)

You can use my code base to find out how to code tooltips with Plotly/Dash
https://github.com/pnlbwh/freesurfer-analysis/blob/7e00327599f4cb6e11561ca413b29b93f88f6a23/scripts/show-stats-table.py#L106-L114

**Comment by jaywonchung** [comment]
That makes a lot of sense. Thanks for the suggestion. Can you take a look at #12?

**Comment by jaywonchung** [comment]
I'll merge for now, but do let me know if you have comments!
