### ISSUE TITLE
response_length of batch inference still decrease

### ISSUE THREAD

**Issue by xzzWZY** [ml-energy/leaderboard-v2#27]
benchmark, batch = 2 of a100 are added and upload to branch "a100_batch", but the response_length of batch = 2 is still shorter than batch = 1, though attention mask is added

**Comment by jaywonchung** [comment]
I don't have the bandwidth to look at this before mid October. Please investigate.

**Comment by jaywonchung** [comment]
There is no information value in this issue. No details, no numbers, and it refers to data that does not exist in the master branch. Closing.
